vich_uploader:
  db_driver: orm

  mappings:
    fileUpload:
      uri_prefix: /assets/vichFiles
      upload_destination: "%kernel.project_dir%/public/assets/vichFiles"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
