vich_uploader:
  db_driver: orm

  mappings:
    fileUpload:
      uri_prefix: /assets/vichFiles
      upload_destination: "%kernel.project_dir%/public/assets/vichFiles"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    collaboration:
      uri_prefix: /assets/img/collaboration
      upload_destination: "%kernel.project_dir%/public/assets/img/collaboration"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true

    avatar:
      uri_prefix: /assets/img/user/avatars
      upload_destination: "%kernel.project_dir%/public/assets/img/user/avatars"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true
      inject_on_load: true

    resume:
      uri_prefix: /assets/resumes
      upload_destination: "%kernel.project_dir%/public/assets/resumes"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true
      inject_on_load: true
